return {
  -- 'folke/noice.nvim',
  -- event = 'VeryLazy',
  -- opts = {
  --   views = {
  --     cmdline_popup = {
  --       border = {
  --         style = 'double',
  --         padding = { 0, 0 },
  --       },
  --       win_options = {
  --         winhighlight = 'NormalFloat:NormalFloat,FloatBorder:NormalFloat',
  --         winblend = 0,
  --       },
  --     },
  --   },
  --   lsp = {
  --     -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
  --     override = {
  --       ['vim.lsp.util.convert_input_to_markdown_lines'] = true,
  --       ['vim.lsp.util.stylize_markdown'] = true,
  --       ['cmpBai.entry.get_documentation'] = true, -- requires hrsh7th/nvim-cmp
  --     },
  --   },
  --   -- you can enable a preset for easier configuration
  --   presets = {
  --     lsp_doc_border = true, -- add a border to hover docs and signature help
  --   },
  -- },
  -- dependencies = {
  --   -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
  --   'MunifTanjim/nui.nvim',
  -- },
}
